/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface SxrInterface extends utils.Interface {
  functions: {
    "add()": FunctionFragment;
    "calc()": FunctionFragment;
    "index()": FunctionFragment;
    "index2()": FunctionFragment;
    "m()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "add" | "calc" | "index" | "index2" | "m"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "add", values?: undefined): string;
  encodeFunctionData(functionFragment: "calc", values?: undefined): string;
  encodeFunctionData(functionFragment: "index", values?: undefined): string;
  encodeFunctionData(functionFragment: "index2", values?: undefined): string;
  encodeFunctionData(functionFragment: "m", values?: undefined): string;

  decodeFunctionResult(functionFragment: "add", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "calc", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "index", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "index2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "m", data: BytesLike): Result;

  events: {};
}

export interface Sxr extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SxrInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    add(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    calc(overrides?: CallOverrides): Promise<[BigNumber]>;

    index(overrides?: CallOverrides): Promise<[BigNumber]>;

    index2(overrides?: CallOverrides): Promise<[BigNumber]>;

    m(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  add(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  calc(overrides?: CallOverrides): Promise<BigNumber>;

  index(overrides?: CallOverrides): Promise<BigNumber>;

  index2(overrides?: CallOverrides): Promise<BigNumber>;

  m(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    add(overrides?: CallOverrides): Promise<void>;

    calc(overrides?: CallOverrides): Promise<BigNumber>;

    index(overrides?: CallOverrides): Promise<BigNumber>;

    index2(overrides?: CallOverrides): Promise<BigNumber>;

    m(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    add(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    calc(overrides?: CallOverrides): Promise<BigNumber>;

    index(overrides?: CallOverrides): Promise<BigNumber>;

    index2(overrides?: CallOverrides): Promise<BigNumber>;

    m(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    add(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    calc(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    index(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    index2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    m(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
