/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC20__factory } from "./IERC20__factory";
export { SpeechLock__factory } from "./SpeechLock__factory";
