/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IInterest, IInterestInterface } from "../IInterest";

const _abi = [
  {
    inputs: [],
    name: "index2",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInterest__factory {
  static readonly abi = _abi;
  static createInterface(): IInterestInterface {
    return new utils.Interface(_abi) as IInterestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInterest {
    return new Contract(address, _abi, signerOrProvider) as IInterest;
  }
}
