/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { Isxr, IsxrInterface } from "../Isxr";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
    ],
    name: "add",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "index2",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Isxr__factory {
  static readonly abi = _abi;
  static createInterface(): IsxrInterface {
    return new utils.Interface(_abi) as IsxrInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Isxr {
    return new Contract(address, _abi, signerOrProvider) as Isxr;
  }
}
