/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  Pendle,
  PendleInterface,
} from "../../../Pendletest/Pendle.sol/Pendle";

const _abi = [
  {
    inputs: [],
    name: "c",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pt",
        type: "address",
      },
      {
        internalType: "address",
        name: "yt",
        type: "address",
      },
    ],
    name: "get",
    outputs: [
      {
        internalType: "uint256",
        name: "d",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052600a60005534801561001557600080fd5b506103b4806100256000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063c3da42b81461003b578063d81e842314610059575b600080fd5b610043610089565b6040516100509190610204565b60405180910390f35b610073600480360381019061006e9190610282565b61008f565b6040516100809190610204565b60405180910390f35b60005481565b60008060405180604001604052808573ffffffffffffffffffffffffffffffffffffffff1681526020018473ffffffffffffffffffffffffffffffffffffffff1681525090506100de816100e7565b91505092915050565b600080826000015173ffffffffffffffffffffffffffffffffffffffff1663a76486b16040518163ffffffff1660e01b8152600401602060405180830381865afa158015610139573d6000803e3d6000fd5b505050506040513d601f19601f8201168201806040525081019061015d91906102ee565b90506000836020015173ffffffffffffffffffffffffffffffffffffffff16636d78a3516040518163ffffffff1660e01b8152600401602060405180830381865afa1580156101b0573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101d491906102ee565b905080826101e2919061034a565b92505050919050565b6000819050919050565b6101fe816101eb565b82525050565b600060208201905061021960008301846101f5565b92915050565b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b600061024f82610224565b9050919050565b61025f81610244565b811461026a57600080fd5b50565b60008135905061027c81610256565b92915050565b600080604083850312156102995761029861021f565b5b60006102a78582860161026d565b92505060206102b88582860161026d565b9150509250929050565b6102cb816101eb565b81146102d657600080fd5b50565b6000815190506102e8816102c2565b92915050565b6000602082840312156103045761030361021f565b5b6000610312848285016102d9565b91505092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b6000610355826101eb565b9150610360836101eb565b92508282019050808211156103785761037761031b565b5b9291505056fea264697066735822122037019f6bc2650703ac2bb7ada59e5829543fb70c5931a1becf176640a93f5a9564736f6c63430008110033";

type PendleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PendleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Pendle__factory extends ContractFactory {
  constructor(...args: PendleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Pendle> {
    return super.deploy(overrides || {}) as Promise<Pendle>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Pendle {
    return super.attach(address) as Pendle;
  }
  override connect(signer: Signer): Pendle__factory {
    return super.connect(signer) as Pendle__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PendleInterface {
    return new utils.Interface(_abi) as PendleInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Pendle {
    return new Contract(address, _abi, signerOrProvider) as Pendle;
  }
}
