/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  InterestManager,
  InterestManagerInterface,
} from "../../Interest.sol/InterestManager";

const _abi = [
  {
    inputs: [],
    name: "index",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "index2",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class InterestManager__factory {
  static readonly abi = _abi;
  static createInterface(): InterestManagerInterface {
    return new utils.Interface(_abi) as InterestManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InterestManager {
    return new Contract(address, _abi, signerOrProvider) as InterestManager;
  }
}
