/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IYT, IYTInterface } from "../../Pendletest/IYT";

const _abi = [
  {
    inputs: [],
    name: "YTsupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IYT__factory {
  static readonly abi = _abi;
  static createInterface(): IYTInterface {
    return new utils.Interface(_abi) as IYTInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IYT {
    return new Contract(address, _abi, signerOrProvider) as IYT;
  }
}
