/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface PTInterface extends utils.Interface {
  functions: {
    "PTsupply()": FunctionFragment;
    "a()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "PTsupply" | "a"): FunctionFragment;

  encodeFunctionData(functionFragment: "PTsupply", values?: undefined): string;
  encodeFunctionData(functionFragment: "a", values?: undefined): string;

  decodeFunctionResult(functionFragment: "PTsupply", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "a", data: BytesLike): Result;

  events: {};
}

export interface PT extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PTInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PTsupply(overrides?: CallOverrides): Promise<[BigNumber]>;

    a(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  PTsupply(overrides?: CallOverrides): Promise<BigNumber>;

  a(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    PTsupply(overrides?: CallOverrides): Promise<BigNumber>;

    a(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    PTsupply(overrides?: CallOverrides): Promise<BigNumber>;

    a(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    PTsupply(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    a(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
