/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBGT } from "./IBGT";
export type { IBeraCrocMultiSwap } from "./IBeraCrocMultiSwap";
export type { ICrocSwapDex } from "./ICrocSwapDex";
export type { IERC20 } from "./IERC20";
export type { IHenloDexRouterV1 } from "./IHenloDexRouterV1";
export type { IStakingVault } from "./IStakingVault";
export type { Malebi } from "./Malebi";
