/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  BGTChanger,
  BGTChangerInterface,
} from "../../AREB.sol/BGTChanger";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "change",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class BGTChanger__factory {
  static readonly abi = _abi;
  static createInterface(): BGTChangerInterface {
    return new utils.Interface(_abi) as BGTChangerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): BGTChanger {
    return new Contract(address, _abi, signerOrProvider) as BGTChanger;
  }
}
