/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IHoneyManager,
  IHoneyManagerInterface,
} from "../../AREB.sol/IHoneyManager";

const _abi = [
  {
    inputs: [],
    name: "addLiquidityAndStake",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimBgtAndBuyBack",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IHoneyManager__factory {
  static readonly abi = _abi;
  static createInterface(): IHoneyManagerInterface {
    return new utils.Interface(_abi) as IHoneyManagerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IHoneyManager {
    return new Contract(address, _abi, signerOrProvider) as IHoneyManager;
  }
}
